# Generated by Django 2.2.11 on 2020-04-14 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', djongo.models.fields.ArrayField(blank=True, model_container=questions.models.Option, null=True)),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('slider', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=55, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
