# Generated by Django 2.2.11 on 2020-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='formId',
            new_name='form',
        ),
    ]
