# Generated by Django 2.1.15 on 2020-04-22 14:48

from django.db import migrations, models
import djongo.models.fields
import liquidIntake.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('beverage', djongo.models.fields.ArrayField(blank=True, model_container=liquidIntake.models.Beverage, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
