# Generated by Django 2.2.11 on 2020-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200427_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exp',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
