# Generated by Django 2.2.11 on 2020-05-12 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('skin_rash', models.BooleanField(default=False)),
                ('skin_swelling', models.BooleanField(default=False)),
                ('blood_pressure_fall', models.BooleanField(default=False)),
                ('consciousness_loss', models.BooleanField(default=False)),
                ('difficult_of_breathing', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=240)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
