# Generated by Django 2.2.11 on 2020-04-14 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeeDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('peeVolume', models.FloatField(blank=True, null=True)),
                ('effortToUrinate', models.IntegerField(blank=True, null=True)),
                ('hasLost', models.BooleanField(default=False)),
                ('isDoingPhysicalActivity', models.BooleanField(default=False)),
                ('referenceVolume', models.FloatField(blank=True, default=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
