# Generated by Django 2.1.15 on 2020-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeeDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('peeVolume', models.FloatField(blank=True, null=True)),
                ('effortToUrinate', models.IntegerField(blank=True, null=True)),
                ('hasLost', models.BooleanField(default=False)),
                ('isDoingPhysicalActivity', models.BooleanField(default=False)),
                ('referenceVolume', models.FloatField(blank=True, default=200, null=True)),
            ],
        ),
    ]
