# Generated by Django 2.1 on 2020-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='nome',
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='Not specified', max_length=55),
        ),
    ]
