# Generated by Django 2.2.11 on 2020-04-07 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=55)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('addressNumber', models.CharField(max_length=15)),
                ('addressComplement', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=15)),
                ('healthEnsurance', models.BooleanField()),
                ('healthEnsuranceCompany', models.CharField(max_length=15)),
                ('healthEnsuranceDescription', models.CharField(max_length=15)),
                ('hasHealthData', models.BooleanField()),
                ('hasPersonalData', models.BooleanField()),
                ('hasPrescription', models.BooleanField()),
                ('hasQrMedicaiton', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
