# Generated by Django 2.2.11 on 2020-04-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0002_auto_20200413_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='hasQrMedicaiton',
            new_name='hasQrMedication',
        ),
    ]
