# Generated by Django 2.2.11 on 2020-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0003_auto_20200413_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='addressComplement',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='hasPersonalData',
            field=models.BooleanField(default=True),
        ),
    ]
