# Generated by Django 2.2.11 on 2020-04-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0005_auto_20200414_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalData.Phone'),
        ),
    ]
