# Generated by Django 2.2.11 on 2020-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0006_auto_20200414_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
