# Generated by Django 2.2.11 on 2020-04-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0007_auto_20200414_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalData.Phone'),
        ),
    ]
