# Generated by Django 2.2.11 on 2020-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0008_auto_20200422_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='birthPlace',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='civilStatus',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='ethnicity',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='familyIncome',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='occupation',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='schooling',
            field=models.CharField(max_length=55),
        ),
    ]
