# Generated by Django 2.2.11 on 2020-04-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0008_auto_20200421_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='personalData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalData.PersonalData'),
        ),
    ]
