# Generated by Django 2.1 on 2020-04-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0009_auto_20200421_2007'),
        ('personalData', '0009_auto_20200422_1632'),
    ]

    operations = [
    ]
