# Generated by Django 2.2.11 on 2020-04-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0009_auto_20200422_1632'),
        ('personalData', '0009_auto_20200421_2007'),
    ]

    operations = [
    ]
